name: "FileCheck.py on Windows"

on:
  push:
    branches: [ "nonsense-branch" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Print Debug info"
      run: |
        python --version
        echo $env:USERPROFILE
        echo $env:PATH
        echo "$PWD"

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip 

    - name: Install dev dependencies
      run: |
        pip install -r requirements.dev.txt

    - name: Run tests
      run: |
        invoke check
      shell: bash
